
-- 회원 정보 --

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
;

DROP TABLE MEMBER_INFO CASCADE CONSTRAINTS;
CREATE TABLE MEMBER_INFO(
  MEMBER_KEY NUMBER PRIMARY KEY,
  EMAIL VARCHAR2(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR2(20) NOT NULL,
  USER_NAME VARCHAR2(18) NOT NULL,
  PHONE_NUMBER VARCHAR2(15) NOT NULL,
  GENDER VARCHAR2(6) CHECK(GENDER IN('남','여','X')),
  BAN VARCHAR2(1) DEFAULT 'N' CHECK(BAN IN('N','Y'))
);

INSERT INTO MEMBER_INFO(MEMBER_KEY,EMAIL,PASSWORD,USER_NAME,PHONE_NUMBER)
VALUES(MEMBER_SEQ.NEXTVAL,'ADMIN','1234','관리자','010-XXXX-XXXX');

INSERT INTO MEMBER_INFO(MEMBER_KEY,EMAIL,PASSWORD,USER_NAME,PHONE_NUMBER,GENDER)
VALUES(MEMBER_SEQ.NEXTVAL,'GEON21H@NAVER.COM','QWER1234~','거니','010-5097-5913','남');

SELECT * FROM MEMBER_INFO;
